### ISSUE TITLE
Chunk Render Bug Fix

### ISSUE THREAD

**Issue by 4ukai** [Ashleyz4/MC_b1.7.3-MegaMod#2]
There is currently a bug with the Ultra mod or actual beta 1.7.3 where chunks after teleporting to some place will stay unrendered allowing you to see through the ground and see caves and stuff.
They won't render unless I use the **F** button to change my fog.

**Comment by 4ukai** [comment]
https://imgur.com/a/1PCiEO1

**Comment by ScarletLovell** [comment]
I'll see what I can do about this one. I know this bug too well.

**Comment by ScarletLovell** [comment]
For now I've added a keybind to force reload all the chunks. Default: CTRL-F
