### ISSUE TITLE
Player View Bug Fix

### ISSUE THREAD

**Issue by portalsam1** [Ashleyz4/MC_b1.7.3-MegaMod#3]
Could you look into the bug that snaps your view to the floor when you exit a chest/chat?

**Comment by ScarletLovell** [comment]
This one actually doesn't happen for me. Can you tell me how to reproduce?

**Comment by portalsam1** [comment]
The bug is very situational and doesn't seem to occur anymore. I used to be able to just say something in chat or close a chest and it would happen 90% of the time. Strange.

**Comment by ScarletLovell** [comment]
Closing for now since it can't be replicated
